[build]
  # 빌드할 디렉토리 (public 폴더의 정적 파일들)
  publish = "public"
  
  # 빌드 명령어 (정적 파일이므로 빌드 불필요)
  command = "echo 'No build required for static files'"

[build.environment]
  NODE_VERSION = "18"

# 리다이렉트 설정 (SPA 라우팅 지원)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = "Not from /api/*"

# API 호출을 외부 백엔드로 프록시
[[redirects]]
  from = "/api/*"
  to = "https://philip-box.onrender.com/api/:splat"
  status = 200
  force = true

# 보안 헤더 설정
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; connect-src 'self' https://philip-box.onrender.com"

# 정적 파일 캐싱
[[headers]]
  for = "/style.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 404 페이지 설정
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404

# 폼 제출 설정 (Netlify Forms 사용 시)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = false
  minify = true
[build.processing.js]
  bundle = false
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true 