services:
  - type: web
    name: mydropbox
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: mydropbox-disk
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1 